
[workers]
target_circulation = 10
http_workers = 2
browser_workers = 2

[http_platforms]

[http_platforms.IpHttp]
max_requests = 10
timeout = 10

[browser_platforms]

[browser_platforms.IpBrowser]
max_requests = 10
timeout = 10
headless = true
