[workers]
target_circulation = 10
http_workers = 1
browser_workers = 1

[http_platforms]

[http_platforms.IpHttp]
max_requests = 10
timeout = 0

[browser_platforms]

[browser_platforms.IpBrowser]
max_requests = 10
timeout = 0
headless = true
