[workers]
target_circulation = 10
http_workers = 1
headless_browser_workers = 1
headed_browser_workers = 1

[http_platforms]

[http_platforms.MyHttp]
max_requests = 10
timeout_ms = 500

[browser_platforms]

[browser_platforms.MyHeadedBrowser]
max_requests = 10
timeout_ms = 500
headless = false

[browser_platforms.MyHeadlessBrowser]
max_requests = 10
timeout_ms = 500
headless = true
